import Head from 'next/head'
import Header from '../components/Header'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Disney+ Hotstar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/D+H_favicon.ico" />
      </Head>
<Header/>
     <h1>Disney +</h1>
    </div>
  )
}
